// MOCK(student): 214 Kangxi radicals — prototype data for the Foundation radical browser.

export interface Radical {
  no: number;
  char: string; // canonical Kangxi form
  pinyin: string; // plain letters, no asterisks/italics markers
  hanviet: string; // Vietnamese radical name from the Hán-Việt column, e.g. "Nhất" — keep parentheses notes out, e.g. for 人 keep just "Nhân"
  strokes: number;
  variants: string[]; // simplified/positional variants from the parentheses in the Radical forms column, e.g. 人 → ["亻","𠆢"], 口 → []. Only CJK chars, no parens. If none, empty array.
}

export const radicals: Radical[] = [
  { no: 1, char: "一", pinyin: "yī", hanviet: "Nhất", strokes: 1, variants: [] },
  { no: 2, char: "丨", pinyin: "gǔn", hanviet: "Cổn", strokes: 1, variants: [] },
  { no: 3, char: "丶", pinyin: "zhǔ", hanviet: "Chủ", strokes: 1, variants: [] },
  { no: 4, char: "丿", pinyin: "piě", hanviet: "Phiệt", strokes: 1, variants: ["乀"] },
  { no: 5, char: "乙", pinyin: "yǐ", hanviet: "Ất", strokes: 1, variants: ["乚", "乛", "⺄"] },
  { no: 6, char: "亅", pinyin: "jué", hanviet: "Quyết", strokes: 1, variants: [] },
  { no: 7, char: "二", pinyin: "èr", hanviet: "Nhị", strokes: 2, variants: [] },
  { no: 8, char: "亠", pinyin: "tóu", hanviet: "Đầu", strokes: 2, variants: [] },
  { no: 9, char: "人", pinyin: "rén", hanviet: "Nhân", strokes: 2, variants: ["亻", "𠆢"] },
  { no: 10, char: "儿", pinyin: "ér", hanviet: "Nhân", strokes: 2, variants: [] },
  { no: 11, char: "入", pinyin: "rù", hanviet: "Nhập", strokes: 2, variants: [] },
  { no: 12, char: "八", pinyin: "bā", hanviet: "Bát", strokes: 2, variants: ["丷"] },
  { no: 13, char: "冂", pinyin: "jiōng", hanviet: "Quynh", strokes: 2, variants: [] },
  { no: 14, char: "冖", pinyin: "mì", hanviet: "Mịch", strokes: 2, variants: [] },
  { no: 15, char: "冫", pinyin: "bīng", hanviet: "Băng", strokes: 2, variants: [] },
  { no: 16, char: "几", pinyin: "jī", hanviet: "Kỷ", strokes: 2, variants: [] },
  { no: 17, char: "凵", pinyin: "kǎn", hanviet: "Khảm", strokes: 2, variants: [] },
  { no: 18, char: "刀", pinyin: "dāo", hanviet: "Đao", strokes: 2, variants: ["刂", "⺈"] },
  { no: 19, char: "力", pinyin: "lì", hanviet: "Lực", strokes: 2, variants: [] },
  { no: 20, char: "勹", pinyin: "bāo", hanviet: "Bao", strokes: 2, variants: [] },
  { no: 21, char: "匕", pinyin: "bǐ", hanviet: "Chủy", strokes: 2, variants: [] },
  { no: 22, char: "匚", pinyin: "fāng", hanviet: "Phương", strokes: 2, variants: [] },
  { no: 23, char: "匸", pinyin: "xǐ/xì", hanviet: "Hệ", strokes: 2, variants: [] },
  { no: 24, char: "十", pinyin: "shí", hanviet: "Thập", strokes: 2, variants: [] },
  { no: 25, char: "卜", pinyin: "bǔ", hanviet: "Bốc", strokes: 2, variants: [] },
  { no: 26, char: "卩", pinyin: "jié", hanviet: "Tiết", strokes: 2, variants: ["㔾"] },
  { no: 27, char: "厂", pinyin: "hǎn", hanviet: "Hán", strokes: 2, variants: [] },
  { no: 28, char: "厶", pinyin: "sī", hanviet: "Tư", strokes: 2, variants: [] },
  { no: 29, char: "又", pinyin: "yòu", hanviet: "Hựu", strokes: 2, variants: [] },
  { no: 30, char: "口", pinyin: "kǒu", hanviet: "Khẩu", strokes: 3, variants: [] },
  { no: 31, char: "囗", pinyin: "wéi", hanviet: "Vi", strokes: 3, variants: [] },
  { no: 32, char: "土", pinyin: "tǔ", hanviet: "Thổ", strokes: 3, variants: [] },
  { no: 33, char: "士", pinyin: "shì", hanviet: "Sĩ", strokes: 3, variants: [] },
  { no: 34, char: "夂", pinyin: "zhǐ", hanviet: "Trĩ", strokes: 3, variants: [] },
  { no: 35, char: "夊", pinyin: "suī", hanviet: "Tuy", strokes: 3, variants: [] },
  { no: 36, char: "夕", pinyin: "xī", hanviet: "Tịch", strokes: 3, variants: [] },
  { no: 37, char: "大", pinyin: "dà", hanviet: "Đại", strokes: 3, variants: [] },
  { no: 38, char: "女", pinyin: "nǚ", hanviet: "Nữ", strokes: 3, variants: [] },
  { no: 39, char: "子", pinyin: "zǐ", hanviet: "Tử", strokes: 3, variants: [] },
  { no: 40, char: "宀", pinyin: "mián", hanviet: "Miên", strokes: 3, variants: [] },
  { no: 41, char: "寸", pinyin: "cùn", hanviet: "Thốn", strokes: 3, variants: [] },
  { no: 42, char: "小", pinyin: "xiǎo", hanviet: "Tiểu", strokes: 3, variants: ["⺌", "⺍"] },
  { no: 43, char: "尢", pinyin: "wāng", hanviet: "Uông", strokes: 3, variants: ["尣"] },
  { no: 44, char: "尸", pinyin: "shī", hanviet: "Thi", strokes: 3, variants: [] },
  { no: 45, char: "屮", pinyin: "chè", hanviet: "Triệt", strokes: 3, variants: [] },
  { no: 46, char: "山", pinyin: "shān", hanviet: "Sơn", strokes: 3, variants: [] },
  { no: 47, char: "巛", pinyin: "chuān", hanviet: "Xuyên", strokes: 3, variants: ["川"] },
  { no: 48, char: "工", pinyin: "gōng", hanviet: "Công", strokes: 3, variants: [] },
  { no: 49, char: "己", pinyin: "jǐ", hanviet: "Kỷ", strokes: 3, variants: [] },
  { no: 50, char: "巾", pinyin: "jīn", hanviet: "Cân", strokes: 3, variants: [] },
  { no: 51, char: "干", pinyin: "gān", hanviet: "Can", strokes: 3, variants: [] },
  { no: 52, char: "幺", pinyin: "yāo", hanviet: "Yêu", strokes: 3, variants: ["么"] },
  { no: 53, char: "广", pinyin: "yǎn", hanviet: "Nghiễm", strokes: 3, variants: [] },
  { no: 54, char: "廴", pinyin: "yǐn", hanviet: "Dẫn", strokes: 3, variants: [] },
  { no: 55, char: "廾", pinyin: "gǒng", hanviet: "Củng", strokes: 3, variants: [] },
  { no: 56, char: "弋", pinyin: "yì", hanviet: "Dặc", strokes: 3, variants: [] },
  { no: 57, char: "弓", pinyin: "gōng", hanviet: "Cung", strokes: 3, variants: [] },
  { no: 58, char: "彐", pinyin: "jì", hanviet: "Ký", strokes: 3, variants: ["彑"] },
  { no: 59, char: "彡", pinyin: "shān", hanviet: "Sam", strokes: 3, variants: [] },
  { no: 60, char: "彳", pinyin: "chì", hanviet: "Sách", strokes: 3, variants: [] },
  { no: 61, char: "心", pinyin: "xīn", hanviet: "Tâm", strokes: 4, variants: ["忄", "⺗"] },
  { no: 62, char: "戈", pinyin: "gē", hanviet: "Qua", strokes: 4, variants: [] },
  { no: 63, char: "戶", pinyin: "hù", hanviet: "Hộ", strokes: 4, variants: ["户", "戸"] },
  { no: 64, char: "手", pinyin: "shǒu", hanviet: "Thủ", strokes: 4, variants: ["扌", "龵"] },
  { no: 65, char: "支", pinyin: "zhī", hanviet: "Chi", strokes: 4, variants: [] },
  { no: 66, char: "攴", pinyin: "pū", hanviet: "Phộc", strokes: 4, variants: ["攵"] },
  { no: 67, char: "文", pinyin: "wén", hanviet: "Văn", strokes: 4, variants: [] },
  { no: 68, char: "斗", pinyin: "dǒu", hanviet: "Đẩu", strokes: 4, variants: [] },
  { no: 69, char: "斤", pinyin: "jīn", hanviet: "Cân", strokes: 4, variants: [] },
  { no: 70, char: "方", pinyin: "fāng", hanviet: "Phương", strokes: 4, variants: [] },
  { no: 71, char: "无", pinyin: "wú", hanviet: "Vô", strokes: 4, variants: ["旡"] },
  { no: 72, char: "日", pinyin: "rì", hanviet: "Nhật", strokes: 4, variants: [] },
  { no: 73, char: "曰", pinyin: "yuē", hanviet: "Viết", strokes: 4, variants: [] },
  { no: 74, char: "月", pinyin: "yuè", hanviet: "Nguyệt", strokes: 4, variants: [] },
  { no: 75, char: "木", pinyin: "mù", hanviet: "Mộc", strokes: 4, variants: [] },
  { no: 76, char: "欠", pinyin: "qiàn", hanviet: "Khiếm", strokes: 4, variants: [] },
  { no: 77, char: "止", pinyin: "zhǐ", hanviet: "Chỉ", strokes: 4, variants: [] },
  { no: 78, char: "歹", pinyin: "dǎi", hanviet: "Đãi", strokes: 4, variants: ["歺"] },
  { no: 79, char: "殳", pinyin: "shū", hanviet: "Thù", strokes: 4, variants: [] },
  { no: 80, char: "毋", pinyin: "wú", hanviet: "Vô", strokes: 4, variants: ["母"] },
  { no: 81, char: "比", pinyin: "bǐ", hanviet: "Tỷ", strokes: 4, variants: [] },
  { no: 82, char: "毛", pinyin: "máo", hanviet: "Mao", strokes: 4, variants: [] },
  { no: 83, char: "氏", pinyin: "shì", hanviet: "Thị", strokes: 4, variants: [] },
  { no: 84, char: "气", pinyin: "qì", hanviet: "Khí", strokes: 4, variants: [] },
  { no: 85, char: "水", pinyin: "shuǐ", hanviet: "Thủy", strokes: 4, variants: ["氵", "氺"] },
  { no: 86, char: "火", pinyin: "huǒ", hanviet: "Hỏa", strokes: 4, variants: ["灬"] },
  { no: 87, char: "爪", pinyin: "zhǎo", hanviet: "Trảo", strokes: 4, variants: ["爫"] },
  { no: 88, char: "父", pinyin: "fù", hanviet: "Phụ", strokes: 4, variants: [] },
  { no: 89, char: "爻", pinyin: "yáo", hanviet: "Hào", strokes: 4, variants: [] },
  { no: 90, char: "爿", pinyin: "qiáng", hanviet: "Tường", strokes: 4, variants: ["丬"] },
  { no: 91, char: "片", pinyin: "piàn", hanviet: "Phiến", strokes: 4, variants: [] },
  { no: 92, char: "牙", pinyin: "yá", hanviet: "Nha", strokes: 4, variants: [] },
  { no: 93, char: "牛", pinyin: "niú", hanviet: "Ngưu", strokes: 4, variants: ["牜", "⺧"] },
  { no: 94, char: "犬", pinyin: "quǎn", hanviet: "Khuyển", strokes: 4, variants: ["犭"] },
  { no: 95, char: "玄", pinyin: "xuán", hanviet: "Huyền", strokes: 5, variants: [] },
  { no: 96, char: "玉", pinyin: "yù", hanviet: "Ngọc", strokes: 5, variants: ["王", "玊"] },
  { no: 97, char: "瓜", pinyin: "guā", hanviet: "Qua", strokes: 5, variants: [] },
  { no: 98, char: "瓦", pinyin: "wǎ", hanviet: "Ngõa", strokes: 5, variants: [] },
  { no: 99, char: "甘", pinyin: "gān", hanviet: "Cam", strokes: 5, variants: [] },
  { no: 100, char: "生", pinyin: "shēng", hanviet: "Sinh", strokes: 5, variants: [] },
  { no: 101, char: "用", pinyin: "yòng", hanviet: "Dụng", strokes: 5, variants: [] },
  { no: 102, char: "田", pinyin: "tián", hanviet: "Điền", strokes: 5, variants: [] },
  { no: 103, char: "疋", pinyin: "pǐ", hanviet: "Thất", strokes: 5, variants: ["⺪"] },
  { no: 104, char: "疒", pinyin: "nè", hanviet: "Nạch", strokes: 5, variants: [] },
  { no: 105, char: "癶", pinyin: "bō", hanviet: "Bát", strokes: 5, variants: [] },
  { no: 106, char: "白", pinyin: "bái", hanviet: "Bạch", strokes: 5, variants: [] },
  { no: 107, char: "皮", pinyin: "pí", hanviet: "Bì", strokes: 5, variants: [] },
  { no: 108, char: "皿", pinyin: "mǐn", hanviet: "Mãnh", strokes: 5, variants: [] },
  { no: 109, char: "目", pinyin: "mù", hanviet: "Mục", strokes: 5, variants: ["⺫"] },
  { no: 110, char: "矛", pinyin: "máo", hanviet: "Mâu", strokes: 5, variants: [] },
  { no: 111, char: "矢", pinyin: "shǐ", hanviet: "Thỉ", strokes: 5, variants: [] },
  { no: 112, char: "石", pinyin: "shí", hanviet: "Thạch", strokes: 5, variants: [] },
  { no: 113, char: "示", pinyin: "shì", hanviet: "Thị", strokes: 5, variants: ["礻"] },
  { no: 114, char: "禸", pinyin: "róu", hanviet: "Nhựu", strokes: 5, variants: [] },
  { no: 115, char: "禾", pinyin: "hé", hanviet: "Hòa", strokes: 5, variants: [] },
  { no: 116, char: "穴", pinyin: "xué", hanviet: "Huyệt", strokes: 5, variants: [] },
  { no: 117, char: "立", pinyin: "lì", hanviet: "Lập", strokes: 5, variants: [] },
  { no: 118, char: "竹", pinyin: "zhú", hanviet: "Trúc", strokes: 6, variants: ["⺮"] },
  { no: 119, char: "米", pinyin: "mǐ", hanviet: "Mễ", strokes: 6, variants: [] },
  { no: 120, char: "糸", pinyin: "mì", hanviet: "Mịch", strokes: 6, variants: ["糹"] },
  { no: 121, char: "缶", pinyin: "fǒu", hanviet: "Phẫu", strokes: 6, variants: [] },
  { no: 122, char: "网", pinyin: "wǎng", hanviet: "Võng", strokes: 6, variants: ["⺲", "罓", "⺳"] },
  { no: 123, char: "羊", pinyin: "yáng", hanviet: "Dương", strokes: 6, variants: ["⺶", "⺷"] },
  { no: 124, char: "羽", pinyin: "yǔ", hanviet: "Vũ", strokes: 6, variants: [] },
  { no: 125, char: "老", pinyin: "lǎo", hanviet: "Lão", strokes: 6, variants: ["耂"] },
  { no: 126, char: "而", pinyin: "ér", hanviet: "Nhi", strokes: 6, variants: [] },
  { no: 127, char: "耒", pinyin: "lěi", hanviet: "Lỗi", strokes: 6, variants: [] },
  { no: 128, char: "耳", pinyin: "ěr", hanviet: "Nhĩ", strokes: 6, variants: [] },
  { no: 129, char: "聿", pinyin: "yù", hanviet: "Duật", strokes: 6, variants: ["⺺", "⺻"] },
  { no: 130, char: "肉", pinyin: "ròu", hanviet: "Nhục", strokes: 6, variants: ["⺼"] },
  { no: 131, char: "臣", pinyin: "chén", hanviet: "Thần", strokes: 6, variants: [] },
  { no: 132, char: "自", pinyin: "zì", hanviet: "Tự", strokes: 6, variants: [] },
  { no: 133, char: "至", pinyin: "zhì", hanviet: "Chí", strokes: 6, variants: [] },
  { no: 134, char: "臼", pinyin: "jiù", hanviet: "Cữu", strokes: 6, variants: [] },
  { no: 135, char: "舌", pinyin: "shé", hanviet: "Thiệt", strokes: 6, variants: [] },
  { no: 136, char: "舛", pinyin: "chuǎn", hanviet: "Suyễn", strokes: 6, variants: [] },
  { no: 137, char: "舟", pinyin: "zhōu", hanviet: "Chu", strokes: 6, variants: [] },
  { no: 138, char: "艮", pinyin: "gèn", hanviet: "Cấn", strokes: 6, variants: [] },
  { no: 139, char: "色", pinyin: "sè", hanviet: "Sắc", strokes: 6, variants: [] },
  { no: 140, char: "艸", pinyin: "cǎo", hanviet: "Thảo", strokes: 6, variants: ["⺿"] },
  { no: 141, char: "虍", pinyin: "hū", hanviet: "Hổ", strokes: 6, variants: [] },
  { no: 142, char: "虫", pinyin: "chóng", hanviet: "Trùng", strokes: 6, variants: [] },
  { no: 143, char: "血", pinyin: "xuè", hanviet: "Huyết", strokes: 6, variants: [] },
  { no: 144, char: "行", pinyin: "xíng", hanviet: "Hành", strokes: 6, variants: [] },
  { no: 145, char: "衣", pinyin: "yī", hanviet: "Y", strokes: 6, variants: ["⻂"] },
  { no: 146, char: "襾", pinyin: "yà", hanviet: "Á", strokes: 6, variants: ["西", "覀"] },
  { no: 147, char: "見", pinyin: "jiàn", hanviet: "Kiến", strokes: 7, variants: [] },
  { no: 148, char: "角", pinyin: "jiǎo", hanviet: "Giác", strokes: 7, variants: ["⻇"] },
  { no: 149, char: "言", pinyin: "yán", hanviet: "Ngôn", strokes: 7, variants: ["訁"] },
  { no: 150, char: "谷", pinyin: "gǔ", hanviet: "Cốc", strokes: 7, variants: [] },
  { no: 151, char: "豆", pinyin: "dòu", hanviet: "Đậu", strokes: 7, variants: [] },
  { no: 152, char: "豕", pinyin: "shǐ", hanviet: "Thỉ", strokes: 7, variants: [] },
  { no: 153, char: "豸", pinyin: "zhì", hanviet: "Trãi", strokes: 7, variants: [] },
  { no: 154, char: "貝", pinyin: "bèi", hanviet: "Bối", strokes: 7, variants: [] },
  { no: 155, char: "赤", pinyin: "chì", hanviet: "Xích", strokes: 7, variants: [] },
  { no: 156, char: "走", pinyin: "zǒu", hanviet: "Tẩu", strokes: 7, variants: [] },
  { no: 157, char: "足", pinyin: "zú", hanviet: "Túc", strokes: 7, variants: ["⻊"] },
  { no: 158, char: "身", pinyin: "shēn", hanviet: "Thân", strokes: 7, variants: [] },
  { no: 159, char: "車", pinyin: "chē", hanviet: "Xa", strokes: 7, variants: [] },
  { no: 160, char: "辛", pinyin: "xīn", hanviet: "Tân", strokes: 7, variants: [] },
  { no: 161, char: "辰", pinyin: "chén", hanviet: "Thần", strokes: 7, variants: [] },
  { no: 162, char: "辵", pinyin: "chuò", hanviet: "Sước", strokes: 7, variants: ["⻌", "⻍", "⻎"] },
  { no: 163, char: "邑", pinyin: "yì", hanviet: "Ấp", strokes: 7, variants: ["⻏"] },
  { no: 164, char: "酉", pinyin: "yǒu", hanviet: "Dậu", strokes: 7, variants: [] },
  { no: 165, char: "釆", pinyin: "biàn", hanviet: "Biện", strokes: 7, variants: [] },
  { no: 166, char: "里", pinyin: "lǐ", hanviet: "Lý", strokes: 7, variants: [] },
  { no: 167, char: "金", pinyin: "jīn", hanviet: "Kim", strokes: 8, variants: ["釒"] },
  { no: 168, char: "長", pinyin: "cháng", hanviet: "Trường", strokes: 8, variants: ["镸"] },
  { no: 169, char: "門", pinyin: "mén", hanviet: "Môn", strokes: 8, variants: [] },
  { no: 170, char: "阜", pinyin: "fù", hanviet: "Phụ", strokes: 8, variants: ["⻖"] },
  { no: 171, char: "隶", pinyin: "lì", hanviet: "Lệ", strokes: 8, variants: [] },
  { no: 172, char: "隹", pinyin: "zhuī", hanviet: "Chuy", strokes: 8, variants: [] },
  { no: 173, char: "雨", pinyin: "yǔ", hanviet: "Vũ", strokes: 8, variants: [] },
  { no: 174, char: "靑", pinyin: "qīng", hanviet: "Thanh", strokes: 8, variants: ["青"] },
  { no: 175, char: "非", pinyin: "fēi", hanviet: "Phi", strokes: 8, variants: [] },
  { no: 176, char: "面", pinyin: "miàn", hanviet: "Diện", strokes: 9, variants: ["靣"] },
  { no: 177, char: "革", pinyin: "gé", hanviet: "Cách", strokes: 9, variants: [] },
  { no: 178, char: "韋", pinyin: "wéi", hanviet: "Vi", strokes: 9, variants: [] },
  { no: 179, char: "韭", pinyin: "jiǔ", hanviet: "Cửu", strokes: 9, variants: [] },
  { no: 180, char: "音", pinyin: "yīn", hanviet: "Âm", strokes: 9, variants: [] },
  { no: 181, char: "頁", pinyin: "yè", hanviet: "Hiệt", strokes: 9, variants: [] },
  { no: 182, char: "風", pinyin: "fēng", hanviet: "Phong", strokes: 9, variants: [] },
  { no: 183, char: "飛", pinyin: "fēi", hanviet: "Phi", strokes: 9, variants: [] },
  { no: 184, char: "食", pinyin: "shí", hanviet: "Thực", strokes: 9, variants: ["飠"] },
  { no: 185, char: "首", pinyin: "shǒu", hanviet: "Thủ", strokes: 9, variants: [] },
  { no: 186, char: "香", pinyin: "xiāng", hanviet: "Hương", strokes: 9, variants: [] },
  { no: 187, char: "馬", pinyin: "mǎ", hanviet: "Mã", strokes: 10, variants: [] },
  { no: 188, char: "骨", pinyin: "gǔ", hanviet: "Cốt", strokes: 10, variants: [] },
  { no: 189, char: "高", pinyin: "gāo", hanviet: "Cao", strokes: 10, variants: ["髙"] },
  { no: 190, char: "髟", pinyin: "biāo", hanviet: "Bưu", strokes: 10, variants: [] },
  { no: 191, char: "鬥", pinyin: "dòu", hanviet: "Đấu", strokes: 10, variants: [] },
  { no: 192, char: "鬯", pinyin: "chàng", hanviet: "Sưởng", strokes: 10, variants: [] },
  { no: 193, char: "鬲", pinyin: "lì", hanviet: "Cách", strokes: 10, variants: [] },
  { no: 194, char: "鬼", pinyin: "guǐ", hanviet: "Quỷ", strokes: 10, variants: [] },
  { no: 195, char: "魚", pinyin: "yú", hanviet: "Ngư", strokes: 11, variants: [] },
  { no: 196, char: "鳥", pinyin: "niǎo", hanviet: "Điểu", strokes: 11, variants: [] },
  { no: 197, char: "鹵", pinyin: "lǔ", hanviet: "Lỗ", strokes: 11, variants: [] },
  { no: 198, char: "鹿", pinyin: "lù", hanviet: "Lộc", strokes: 11, variants: [] },
  { no: 199, char: "麥", pinyin: "mài", hanviet: "Mạch", strokes: 11, variants: [] },
  { no: 200, char: "麻", pinyin: "má", hanviet: "Ma", strokes: 11, variants: [] },
  { no: 201, char: "黃", pinyin: "huáng", hanviet: "Hoàng", strokes: 12, variants: [] },
  { no: 202, char: "黍", pinyin: "shǔ", hanviet: "Thử", strokes: 12, variants: [] },
  { no: 203, char: "黑", pinyin: "hēi", hanviet: "Hắc", strokes: 12, variants: [] },
  { no: 204, char: "黹", pinyin: "zhǐ", hanviet: "Chỉ", strokes: 12, variants: [] },
  { no: 205, char: "黽", pinyin: "mǐn", hanviet: "Mãnh", strokes: 13, variants: [] },
  { no: 206, char: "鼎", pinyin: "dǐng", hanviet: "Đỉnh", strokes: 13, variants: [] },
  { no: 207, char: "鼓", pinyin: "gǔ", hanviet: "Cổ", strokes: 13, variants: [] },
  { no: 208, char: "鼠", pinyin: "shǔ", hanviet: "Thử", strokes: 13, variants: [] },
  { no: 209, char: "鼻", pinyin: "bí", hanviet: "Tị", strokes: 14, variants: [] },
  { no: 210, char: "齊", pinyin: "qí", hanviet: "Tề", strokes: 14, variants: ["斉"] },
  { no: 211, char: "齒", pinyin: "chǐ", hanviet: "Xỉ", strokes: 15, variants: [] },
  { no: 212, char: "龍", pinyin: "lóng", hanviet: "Long", strokes: 16, variants: [] },
  { no: 213, char: "龜", pinyin: "guī", hanviet: "Quy", strokes: 16, variants: [] },
  { no: 214, char: "龠", pinyin: "yuè", hanviet: "Dược", strokes: 17, variants: [] },
];
