/**
 * The subset of `docs/api/API_ERROR_CODES.md` this app actually emits.
 *
 * Codes are copied, never invented — API_ERROR_CODES.md is the registry and adding
 * to it is a documentation decision, not a coding one. Codes the registry marks
 * *proposed, not agreed* are deliberately absent: `TOO_MANY_REQUESTS` among them,
 * which is why no rate limiting is wired up yet (01-auth.md §16).
 */
export const ErrorCode = {
  // Auth (registry § Auth Errors)
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',

  // User (registry § User Errors)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_APPROVED: 'USER_ALREADY_APPROVED',

  // Class (registry § Class Errors)
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
  CLASS_ACCESS_DENIED: 'CLASS_ACCESS_DENIED',
  CLASS_ALREADY_ARCHIVED: 'CLASS_ALREADY_ARCHIVED',
  CLASS_ENROLL_CODE_INVALID: 'CLASS_ENROLL_CODE_INVALID',
  CLASS_ALREADY_ENROLLED: 'CLASS_ALREADY_ENROLLED',
  CLASS_NOT_ENROLLED: 'CLASS_NOT_ENROLLED',

  // Lesson (registry § Lesson Errors)
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  LESSON_ACCESS_DENIED: 'LESSON_ACCESS_DENIED',
  LESSON_ORDER_INDEX_CONFLICT: 'LESSON_ORDER_INDEX_CONFLICT',

  // Validation + fallbacks (registry § Validation Errors, § Fallback Errors)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * HTTP status for each code, exactly as the registry tables state it.
 */
export const ERROR_STATUS: Record<ErrorCodeValue, number> = {
  AUTH_EMAIL_EXISTS: 409,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_ACCOUNT_PENDING: 403,
  AUTH_ACCOUNT_SUSPENDED: 403,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_REFRESH_INVALID: 401,
  AUTH_INSUFFICIENT_ROLE: 403,
  USER_NOT_FOUND: 404,
  USER_ALREADY_APPROVED: 409,
  CLASS_NOT_FOUND: 404,
  CLASS_ACCESS_DENIED: 403,
  CLASS_ALREADY_ARCHIVED: 400,
  CLASS_ENROLL_CODE_INVALID: 404,
  CLASS_ALREADY_ENROLLED: 409,
  CLASS_NOT_ENROLLED: 400,
  LESSON_NOT_FOUND: 404,
  LESSON_ACCESS_DENIED: 403,
  LESSON_ORDER_INDEX_CONFLICT: 409,
  VALIDATION_ERROR: 400,
  DUPLICATE_ENTRY: 409,
  INTERNAL_SERVER_ERROR: 500,
};
