/**
 * The subset of `docs/api/API_ERROR_CODES.md` this app actually emits.
 *
 * Codes are copied, never invented — API_ERROR_CODES.md is the registry and adding
 * to it is a documentation decision, not a coding one. Codes the registry marks
 * *proposed, not agreed* are deliberately absent: `TOO_MANY_REQUESTS` among them,
 * which is why no rate limiting is wired up yet (01-auth.md §16).
 */
export const ErrorCode = {
  // Auth (registry § Auth Errors)
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_INSUFFICIENT_ROLE: 'AUTH_INSUFFICIENT_ROLE',
  AUTH_TOO_MANY_REQUESTS: 'AUTH_TOO_MANY_REQUESTS',

  // User (registry § User Errors)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_APPROVED: 'USER_ALREADY_APPROVED',
  USER_ALREADY_SUSPENDED: 'USER_ALREADY_SUSPENDED',
  USER_ALREADY_ACTIVE: 'USER_ALREADY_ACTIVE',
  USER_INVALID_STATUS_TRANSITION: 'USER_INVALID_STATUS_TRANSITION',

  // Class (registry § Class Errors)
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
  CLASS_ACCESS_DENIED: 'CLASS_ACCESS_DENIED',
  CLASS_ALREADY_ARCHIVED: 'CLASS_ALREADY_ARCHIVED',
  CLASS_ENROLL_CODE_INVALID: 'CLASS_ENROLL_CODE_INVALID',
  CLASS_ALREADY_ENROLLED: 'CLASS_ALREADY_ENROLLED',
  CLASS_NOT_ENROLLED: 'CLASS_NOT_ENROLLED',

  // Lesson (registry § Lesson Errors)
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  LESSON_ACCESS_DENIED: 'LESSON_ACCESS_DENIED',
  LESSON_ORDER_INDEX_CONFLICT: 'LESSON_ORDER_INDEX_CONFLICT',

  // Question bank (registry § Question Errors). MongoDB-backed.
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  QUESTION_NOT_OWNER: 'QUESTION_NOT_OWNER',
  QUESTION_AUDIO_REQUIRED: 'QUESTION_AUDIO_REQUIRED',

  // Session review & teacher sessions (registry § Session Review Errors)
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_REVIEWED: 'SESSION_ALREADY_REVIEWED',
  SESSION_REJECT_REASON_REQUIRED: 'SESSION_REJECT_REASON_REQUIRED',
  SESSION_INVALID_TRANSITION: 'SESSION_INVALID_TRANSITION',

  // Rates (registry § Rate Errors)
  RATE_NOT_FOUND: 'RATE_NOT_FOUND',
  RATE_EFFECTIVE_DATE_IN_PAST: 'RATE_EFFECTIVE_DATE_IN_PAST',
  RATE_IMMUTABLE: 'RATE_IMMUTABLE',

  // Payroll (registry § Payroll Errors)
  PAYROLL_SESSION_NOT_FOUND: 'PAYROLL_SESSION_NOT_FOUND',
  PAYROLL_SESSION_NOT_COMPLETED: 'PAYROLL_SESSION_NOT_COMPLETED',
  PAYROLL_PERIOD_NOT_FOUND: 'PAYROLL_PERIOD_NOT_FOUND',
  PAYROLL_PERIOD_FINALIZED: 'PAYROLL_PERIOD_FINALIZED',
  PAYROLL_PERIOD_ALREADY_PAID: 'PAYROLL_PERIOD_ALREADY_PAID',
  PAYROLL_PERIOD_DUPLICATE: 'PAYROLL_PERIOD_DUPLICATE',
  PAYROLL_PERIOD_OVERLAP: 'PAYROLL_PERIOD_OVERLAP',
  PAYROLL_SESSION_HOURLY_MISSING_TIME: 'PAYROLL_SESSION_HOURLY_MISSING_TIME',

  // Invoice & Billing (registry § Invoice Errors)
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_VOID: 'INVOICE_ALREADY_VOID',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_PERIOD_DUPLICATE: 'INVOICE_PERIOD_DUPLICATE',
  INVOICE_NO_TUITION_RATE: 'INVOICE_NO_TUITION_RATE',
  INVOICE_PAYMENT_EXCEEDS_TOTAL: 'INVOICE_PAYMENT_EXCEEDS_TOTAL',
  INVOICE_BATCH_PARTIAL_FAILURE: 'INVOICE_BATCH_PARTIAL_FAILURE',
  INVOICE_VOID_WITH_PAYMENTS_FORBIDDEN: 'INVOICE_VOID_WITH_PAYMENTS_FORBIDDEN',
  INVOICE_PREVIEW_HASH_MISMATCH: 'INVOICE_PREVIEW_HASH_MISMATCH',

  // AI / Gemini (registry § AI / Gemini Errors)
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',
  AI_KEY_INVALID: 'AI_KEY_INVALID',
  AI_GRADING_FAILED: 'AI_GRADING_FAILED',

  // Idempotency (registry § Idempotency Errors)
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',

  // Validation + fallbacks (registry § Validation Errors, § Fallback Errors)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * HTTP status for each code, exactly as the registry tables state it.
 */
export const ERROR_STATUS: Record<ErrorCodeValue, number> = {
  AUTH_EMAIL_EXISTS: 409,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_ACCOUNT_PENDING: 403,
  AUTH_ACCOUNT_SUSPENDED: 403,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_REFRESH_INVALID: 401,
  AUTH_INSUFFICIENT_ROLE: 403,
  AUTH_TOO_MANY_REQUESTS: 429,
  USER_NOT_FOUND: 404,
  USER_ALREADY_APPROVED: 409,
  USER_ALREADY_SUSPENDED: 409,
  USER_ALREADY_ACTIVE: 409,
  USER_INVALID_STATUS_TRANSITION: 400,
  CLASS_NOT_FOUND: 404,
  CLASS_ACCESS_DENIED: 403,
  CLASS_ALREADY_ARCHIVED: 400,
  CLASS_ENROLL_CODE_INVALID: 404,
  CLASS_ALREADY_ENROLLED: 409,
  CLASS_NOT_ENROLLED: 400,
  LESSON_NOT_FOUND: 404,
  LESSON_ACCESS_DENIED: 403,
  LESSON_ORDER_INDEX_CONFLICT: 409,
  QUESTION_NOT_FOUND: 404,
  QUESTION_NOT_OWNER: 403,
  QUESTION_AUDIO_REQUIRED: 400,
  SESSION_NOT_FOUND: 404,
  SESSION_ALREADY_REVIEWED: 409,
  SESSION_REJECT_REASON_REQUIRED: 400,
  SESSION_INVALID_TRANSITION: 409,
  RATE_NOT_FOUND: 404,
  RATE_EFFECTIVE_DATE_IN_PAST: 400,
  RATE_IMMUTABLE: 409,
  PAYROLL_SESSION_NOT_FOUND: 404,
  PAYROLL_SESSION_NOT_COMPLETED: 400,
  PAYROLL_PERIOD_NOT_FOUND: 404,
  PAYROLL_PERIOD_FINALIZED: 409,
  PAYROLL_PERIOD_ALREADY_PAID: 409,
  PAYROLL_PERIOD_DUPLICATE: 409,
  PAYROLL_PERIOD_OVERLAP: 409,
  PAYROLL_SESSION_HOURLY_MISSING_TIME: 400,
  INVOICE_NOT_FOUND: 404,
  INVOICE_ALREADY_VOID: 409,
  INVOICE_ALREADY_PAID: 409,
  INVOICE_PERIOD_DUPLICATE: 409,
  INVOICE_NO_TUITION_RATE: 400,
  INVOICE_PAYMENT_EXCEEDS_TOTAL: 400,
  INVOICE_BATCH_PARTIAL_FAILURE: 422,
  INVOICE_VOID_WITH_PAYMENTS_FORBIDDEN: 409,
  INVOICE_PREVIEW_HASH_MISMATCH: 409,
  AI_QUOTA_EXCEEDED: 429,
  AI_KEY_INVALID: 401,
  AI_GRADING_FAILED: 502,
  IDEMPOTENCY_KEY_CONFLICT: 422,
  VALIDATION_ERROR: 400,
  DUPLICATE_ENTRY: 409,
  INTERNAL_SERVER_ERROR: 500,
};
